# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-02 20:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.datetime_safe


class Migration(migrations.Migration):

    dependencies = [
        ('inga', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chlorophyll',
            name='date',
            field=models.DateField(default=django.utils.datetime_safe.datetime.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='chlorophyll',
            name='plant',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='inga.Plant'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='expansion',
            name='date',
            field=models.DateField(default=django.utils.datetime_safe.datetime.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='expansion',
            name='plant',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='inga.Plant'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hairs',
            name='date',
            field=models.DateField(default=django.utils.datetime_safe.datetime.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hairs',
            name='plant',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='inga.Plant'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='toughness',
            name='date',
            field=models.DateField(default=django.utils.datetime_safe.datetime.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='toughness',
            name='plant',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='inga.Plant'),
            preserve_default=False,
        ),
    ]
