# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-19 23:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inga', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='herbivorecollection',
            name='analysis',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='herbivorecollection',
            name='collection_number',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inga.HerbivoreCollectionObservation'),
        ),
        migrations.AlterField(
            model_name='herbivorecollection',
            name='motu',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='herbivorecollection',
            name='photo',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='herbivorespecies',
            name='bin',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='herbivorespecies',
            name='blasting_family',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='herbivorespecies',
            name='blasting_genus',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='herbivorespecies',
            name='blasting_subfamily',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='herbivorespecies',
            name='consensus_sequence',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='herbivorespecies',
            name='ibol',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='herbivorespecies',
            name='la_motu',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='herbivorespecies',
            name='motu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inga.HerbivoreCollection'),
        ),
        migrations.AlterField(
            model_name='herbivorespecies',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='herbivorespecies',
            name='notes_on_host',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='herbivorespecies',
            name='percentage_match_on_BOLD',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
