# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-07 14:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inga', '0003_auto_20160705_1455'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extraction',
            name='box',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='extraction',
            name='chemist',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='extraction',
            name='dry_marc_weight',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='extraction',
            name='dry_weight',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='extraction',
            name='empty_vial_weight',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='extraction',
            name='extraction_notebook_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='extraction',
            name='final_weight',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='extraction',
            name='mass_extracted',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='extraction',
            name='method',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='extraction',
            name='notebook_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='extraction',
            name='other_chemistry',
            field=models.ManyToManyField(blank=True, related_name='other_chemistry', to='inga.Chemistry'),
        ),
        migrations.AlterField(
            model_name='extraction',
            name='page_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='extraction',
            name='parent_extraction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inga.Extraction'),
        ),
        migrations.AlterField(
            model_name='extraction',
            name='percent_extracted',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='extraction',
            name='proportion_remaining',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
