# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-20 00:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inga', '0003_auto_20170319_2355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='herbivorecollectionobservation',
            name='field',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inga.Field'),
        ),
        migrations.AlterField(
            model_name='herbivorecollectionobservation',
            name='herbivores_collected',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='herbivorecollectionobservation',
            name='herbivores_total',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='herbivorecollectionobservation',
            name='preliminary_family',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
