# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-20 00:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inga', '0004_auto_20170320_0007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='herbivorecollectionobservation',
            name='collection_number',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inga.HerbivoreCollection'),
        ),
        migrations.AlterField(
            model_name='herbivorecollectionobservation',
            name='field',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inga.Field'),
        ),
    ]
