# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-11 16:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inga', '0006_auto_20160711_1833'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plantspecies',
            name='authority',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='plantspecies',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='plantspecies',
            name='genus',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='plantspecies',
            name='note_chemistry_analysis',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='plantspecies',
            name='old_species_number',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='plantspecies',
            name='species_code',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='plantspecies',
            name='species_name',
            field=models.TextField(blank=True, null=True),
        ),
    ]
