# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-03-20 08:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inga', '0006_auto_20170320_0449'),
    ]

    operations = [
        migrations.AddField(
            model_name='hplcresult',
            name='project',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='extraction',
            name='chemist',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='extractionresultweight',
            name='trait',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='extrafloralnectaries',
            name='color',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='herbivorecollectionobservation',
            name='preliminary_family',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hplcresult',
            name='column_used',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='hplcresult',
            name='method',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='hplcresult',
            name='sample_type',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='plantvoucher',
            name='voucher',
            field=models.CharField(max_length=30),
        ),
    ]
