# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-12 12:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inga', '0007_auto_20160711_1842'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlantVoucher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voucher', models.CharField(max_length=10)),
            ],
        ),
        migrations.AlterField(
            model_name='plant',
            name='code',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='plant',
            name='collectors',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='plant',
            name='date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='plant',
            name='date_dna_sent',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='plant',
            name='dbh',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='plant',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='plant',
            name='dna',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='plant',
            name='flower_color',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='plant',
            name='height',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='plant',
            name='herbarium_sample',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='plant',
            name='lh',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='plant',
            name='light',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='plant',
            name='new_leaves',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='plant',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inga.Site'),
        ),
        migrations.AlterField(
            model_name='plant',
            name='size',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='plant',
            name='species',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inga.PlantSpecies'),
        ),
        migrations.AlterField(
            model_name='plant',
            name='vouchers',
            field=models.ManyToManyField(blank=True, null=True, to='inga.Voucher'),
        ),
        migrations.AddField(
            model_name='plantvoucher',
            name='plant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inga.Plant'),
        ),
    ]
