# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-12 12:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inga', '0009_auto_20160712_1431'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='site',
            name='site_id',
        ),
        migrations.AddField(
            model_name='site',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='site',
            name='site',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
