# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-03-20 09:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inga', '0009_auto_20170320_0943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extraction',
            name='chemistry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inga.Chemistry'),
        ),
    ]
