# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-03-20 19:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inga', '0010_auto_20170320_0945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='site',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
