# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-16 23:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inga', '0010_auto_20160712_1457'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chemistry',
            name='age',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='chemistry',
            name='box_number',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='chemistry',
            name='cur_w',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='chemistry',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='chemistry',
            name='dbh',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='chemistry',
            name='exp_max',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='chemistry',
            name='exp_min',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='chemistry',
            name='extracted',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='chemistry',
            name='fwg',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='chemistry',
            name='height',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='chemistry',
            name='light',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='chemistry',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='chemistry',
            name='number_plants',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='chemistry',
            name='size',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='chemistry',
            name='status',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='chemistry',
            name='unused_material',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='chemistry',
            name='use_field',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='chemistry',
            name='vial_w',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
