# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-04-28 19:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inga', '0012_auto_20170428_0655'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlantSpeciesHistorical',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated', models.DateField(auto_now=True)),
                ('generic', models.BooleanField(default=False)),
                ('old_species_number', models.TextField(blank=True, null=True)),
                ('genus', models.TextField(blank=True, null=True)),
                ('species_name', models.TextField(blank=True, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('note_chemistry_analysis', models.TextField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='plantspecies',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='plantspecies',
            name='note_chemistry_analysis',
        ),
        migrations.RemoveField(
            model_name='plantspecies',
            name='old_species_number',
        ),
        migrations.AddField(
            model_name='plantspecieshistorical',
            name='species_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inga.PlantSpecies'),
        ),
    ]
