# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-01 22:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inga', '0013_auto_20160718_1410'),
    ]

    operations = [
        migrations.AddField(
            model_name='extrafloralnectaries',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='chlorophyll',
            name='chl_mg_dm2',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='chlorophyll',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='chlorophyll',
            name='light',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='chlorophyll',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='chlorophyll',
            name='percent_exposed',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='chlorophyll',
            name='size',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='chlorophyll',
            name='spadd',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='extrafloralnectaries',
            name='apical_mm',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='extrafloralnectaries',
            name='basal_mm',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='extrafloralnectaries',
            name='color',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='extrafloralnectaries',
            name='efn_type',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='extrafloralnectaries',
            name='mid_mm',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='extrafloralnectaries',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='extrafloralnectaries',
            name='shape',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='extrafloralnectaries',
            name='xEFN_mm',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
