# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-04-30 06:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inga', '0013_auto_20170428_1929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extrafloralnectaries',
            name='plant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inga.Plant'),
        ),
    ]
