# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-04-30 08:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inga', '0014_auto_20170430_0649'),
    ]

    operations = [
        migrations.AddField(
            model_name='field',
            name='old_table_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
