# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-06 02:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inga', '0015_auto_20161018_0244'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeatureTableRawData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated', models.DateField(auto_now=True)),
                ('generic', models.BooleanField(default=False)),
                ('species_code_sample', models.CharField(max_length=30)),
                ('RT', models.FloatField()),
                ('MZ', models.FloatField()),
                ('PC_ID', models.CharField(max_length=30)),
                ('TIC', models.FloatField()),
                ('Date_Update', models.DateField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PC_ID',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated', models.DateField(auto_now=True)),
                ('generic', models.BooleanField(default=False)),
                ('MZ_RT', models.TextField(blank=True, null=True)),
                ('Percent_TIC', models.FloatField(blank=True, null=True)),
                ('ms_ms_spec', models.TextField(blank=True, null=True)),
                ('ms_ms_spec_id', models.IntegerField(blank=True, null=True)),
                ('PC_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inga.FeatureTableRawData')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Tyrosine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated', models.DateField(auto_now=True)),
                ('generic', models.BooleanField(default=False)),
                ('percent_tyrosine', models.IntegerField()),
                ('file', models.TextField()),
                ('calibration', models.IntegerField()),
                ('date', models.DateField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='chemistry',
            name='generic',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='chlorophyll',
            name='generic',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='converted',
            name='generic',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dna',
            name='generic',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='expansion',
            name='generic',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='extraction',
            name='generic',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='extractionresultweight',
            name='generic',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='extrafloralnectaries',
            name='generic',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='field',
            name='generic',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='hairs',
            name='generic',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='herbivorecollectionobservation',
            name='generic',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='herbivoredna',
            name='generic',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='herbivorephotos',
            name='generic',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='herbivorespecies',
            name='generic',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='herbivorespeciesobservation',
            name='generic',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='herbivorevoucher',
            name='generic',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='herbivory',
            name='generic',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='hplcresult',
            name='generic',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='leafmassarea',
            name='generic',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='location',
            name='generic',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='method',
            name='generic',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='methodresult',
            name='generic',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='nitrogen',
            name='generic',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='plant',
            name='generic',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='plantdna',
            name='generic',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='plantphoto',
            name='generic',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='plantspecies',
            name='generic',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='plantvoucher',
            name='generic',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='raw',
            name='generic',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='site',
            name='generic',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='toughness',
            name='generic',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='toughness',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='toughness',
            name='toughness',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='uplcresult',
            name='generic',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='voucher',
            name='generic',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='chemistry',
            name='extracted',
            field=models.NullBooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='extrafloralnectaries',
            name='color',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='extrafloralnectaries',
            name='plant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inga.Plant'),
        ),
        migrations.AlterField(
            model_name='herbivorecollectionobservation',
            name='species_code',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='herbivorephotos',
            name='voucher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inga.HerbivoreVoucher'),
        ),
        migrations.AlterField(
            model_name='herbivorevoucher',
            name='voucher',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='herbivory',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inga.Location'),
        ),
        migrations.AlterField(
            model_name='leafmassarea',
            name='age',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='leafmassarea',
            name='area',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='leafmassarea',
            name='drying_method',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='leafmassarea',
            name='dw_area_g',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='leafmassarea',
            name='dw_g',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='leafmassarea',
            name='inches',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='leafmassarea',
            name='light',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='leafmassarea',
            name='plant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inga.Plant'),
        ),
        migrations.AlterField(
            model_name='leafmassarea',
            name='size',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='nitrogen',
            name='age',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='nitrogen',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='nitrogen',
            name='percent_nitrogen',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='nitrogen',
            name='percentage_of_expansion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='nitrogen',
            name='sample_number_for_nitrogen_analysis',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='nitrogen',
            name='subsample_weight',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='nitrogen',
            name='weight_after_grounding',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='nitrogen',
            name='weight_before_grounding',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='plant',
            name='plant_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tyrosine',
            name='extraction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inga.Extraction'),
        ),
        migrations.AddField(
            model_name='featuretablerawdata',
            name='sample',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inga.UPLCResult'),
        ),
    ]
