# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-06 05:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inga', '0016_auto_20170106_0222'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='extraction',
            name='parent_extraction',
        ),
    ]
