# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-30 21:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inga', '0016_auto_20170501_0851'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expansion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated', models.DateField(auto_now=True)),
                ('generic', models.BooleanField(default=False)),
                ('collectors', models.CharField(blank=True, db_column='Collectors', max_length=25, null=True)),
                ('date', models.DateField()),
                ('lh_field', models.IntegerField(blank=True, db_column='LH#', null=True)),
                ('day1', models.IntegerField(blank=True, db_column='Day1', null=True)),
                ('hour1', models.IntegerField(blank=True, db_column='Hour1', null=True)),
                ('area1', models.IntegerField(blank=True, db_column='Area1', null=True)),
                ('day2', models.IntegerField(blank=True, db_column='Day2', null=True)),
                ('hour2', models.IntegerField(blank=True, db_column='Hour2', null=True)),
                ('age2', models.IntegerField(blank=True, db_column='Age2', null=True)),
                ('area2', models.IntegerField(blank=True, db_column='Area2', null=True)),
                ('day3', models.IntegerField(blank=True, db_column='Day3', null=True)),
                ('hour3', models.IntegerField(blank=True, db_column='Hour3', null=True)),
                ('age3', models.IntegerField(blank=True, db_column='Age3', null=True)),
                ('area3', models.IntegerField(blank=True, db_column='Area3', null=True)),
                ('day4', models.IntegerField(blank=True, db_column='Day4', null=True)),
                ('hour4', models.IntegerField(blank=True, db_column='Hour4', null=True)),
                ('age4', models.IntegerField(blank=True, db_column='Age4', null=True)),
                ('area4', models.IntegerField(blank=True, db_column='Area4', null=True)),
                ('day5', models.IntegerField(blank=True, db_column='Day5', null=True)),
                ('hour5', models.IntegerField(blank=True, db_column='Hour5', null=True)),
                ('age5', models.IntegerField(blank=True, db_column='Age5', null=True)),
                ('area5', models.IntegerField(blank=True, db_column='Area5', null=True)),
                ('final', models.IntegerField(blank=True, db_column='Final', null=True)),
                ('age1percent', models.IntegerField(blank=True, db_column='Age1percent', null=True)),
                ('dt2', models.IntegerField(blank=True, null=True)),
                ('age2percent', models.IntegerField(blank=True, null=True)),
                ('dt3', models.IntegerField(blank=True, db_column='DT3', null=True)),
                ('age3percent', models.IntegerField(blank=True, db_column='Age3percent', null=True)),
                ('dt4', models.IntegerField(blank=True, db_column='DT4', null=True)),
                ('age4percent', models.IntegerField(blank=True, db_column='Age4percent', null=True)),
                ('dt5', models.IntegerField(blank=True, db_column='DT5', null=True)),
                ('age5percent', models.IntegerField(blank=True, db_column='Age5percent', null=True)),
                ('x_dt_d_field', models.IntegerField(blank=True, db_column='x-DT(d)', null=True)),
                ('x_exp_percent', models.IntegerField(blank=True, db_column='x-Exp-percent', null=True)),
                ('spp', models.IntegerField(blank=True, null=True)),
                ('notes2', models.IntegerField(blank=True, db_column='Notes2', null=True)),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inga.Plant')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='Method',
        ),
        migrations.AlterField(
            model_name='extraction',
            name='method',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
