# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-07-23 04:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inga', '0017_auto_20170530_2155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plantspecieshistorical',
            name='species_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historical', to='inga.PlantSpecies'),
        ),
    ]
