# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-02 04:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inga', '0017_auto_20170530_2155'),
    ]

    operations = [
        migrations.RenameField(
            model_name='uplcresult',
            old_name='diva',
            new_name='file_name',
        ),
        migrations.AlterField(
            model_name='plantspecieshistorical',
            name='species_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historical', to='inga.PlantSpecies'),
        ),
    ]
