# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-08-02 04:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inga', '0018_auto_20170802_0406'),
        ('inga', '0018_auto_20170723_0453'),
    ]

    operations = [
    ]
