# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-12-20 08:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inga', '0019_merge_20170802_0410'),
    ]

    operations = [
        migrations.AddField(
            model_name='tyrosine',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='uplcresult',
            name='blank',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='uplcresult',
            name='rti',
            field=models.TextField(blank=True, null=True),
        ),
    ]
