# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-01-04 06:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inga', '0020_auto_20171220_0801'),
    ]

    operations = [
        migrations.CreateModel(
            name='HairMeasurement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated', models.DateField(auto_now=True)),
                ('generic', models.BooleanField(default=False)),
                ('measurement_name', models.TextField()),
                ('value', models.FloatField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RenameField(
            model_name='leafmassarea',
            old_name='area',
            new_name='area_cm2',
        ),
        migrations.RenameField(
            model_name='leafmassarea',
            old_name='dw_area_g',
            new_name='dw_area_g_cm2',
        ),
        migrations.AddField(
            model_name='hairs',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='expansion',
            name='lh_field',
            field=models.TextField(blank=True, db_column='LH#', null=True),
        ),
        migrations.AlterField(
            model_name='expansion',
            name='notes2',
            field=models.TextField(blank=True, db_column='Notes2', null=True),
        ),
        migrations.AddField(
            model_name='hairmeasurement',
            name='hairs',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inga.Hairs'),
        ),
    ]
