# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-06 02:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oldinga', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tyrosine',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('extraction_number', models.IntegerField(blank=True, db_column='Extraction_Number', null=True)),
                ('percent_tyrosine', models.IntegerField(db_column='Percent_Tyrosine')),
                ('link_to_file', models.CharField(db_column='Link_to_File', max_length=155)),
                ('calibration_number', models.IntegerField(db_column='Calibration_Number')),
                ('month', models.CharField(blank=True, db_column='Month', max_length=11, null=True)),
                ('day', models.IntegerField(blank=True, db_column='Day', null=True)),
                ('year', models.IntegerField(blank=True, db_column='Year', null=True)),
                ('updated', models.DateTimeField()),
            ],
            options={
                'managed': False,
                'db_table': 'tyrosine',
            },
        ),
    ]
