# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-07-23 04:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oldinga', '0004_specieshistorical'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='expansion',
            table='Expansion_old',
        ),
    ]
