# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-02 17:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oldinga', '0006_merge_20170802_0410'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='expansion',
            table='Expansion',
        ),
    ]
