# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-06 07:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingaweb', '0002_remove_batch_error_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='headers',
            field=models.TextField(blank=True, null=True),
        ),
    ]
